version: '3.8'
services:
  server:
    image: idealers_app
    build:
      context: .
      dockerfile: Dockerfile
    command: python idealers/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/app/
    env_file:
      - ./app/.env
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app/.env
    ports:
      - 5432:5432
volumes:
    postgres_data: